owner: shirosweets
repo: upptime

sites:
  - name: API Core PAGOS360 Sandbox
    url: https://api.sandbox.pagos360.com/
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

assignees:
  - shirosweets

status-website:
  baseUrl: /upptime
  logoUrl: assets/health.svg
  name: Upptime
  introTitle: "**Upptime** is monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
